Tabs
AlyonaY/fe-46-yarmak pull request #11
Opened 2023-02-28 09:04 UTC by AlyonaY

2023-02-28 09:16 UTC, UladTeachMeSkills requested changes

2023-02-28 09:16 UTC, UladTeachMeSkills commented on exit_project/main.html
> +              <label class="tabs__item" id="tab-three" for="three">Tab 3</label>
Для чего тебе в label - id?

2023-02-28 09:16 UTC, UladTeachMeSkills commented on exit_project/main.html
> +                  src="/fe-46-yarmak/exit_project/images/liberty_statue.svg"
Адрес...

2023-02-28 09:16 UTC, UladTeachMeSkills commented on exit_project/main.html
> +                  src="/fe-46-yarmak/exit_project/images/liberty_statue.svg"
same

2023-02-28 09:16 UTC, UladTeachMeSkills commented on exit_project/main.html
> +                  <button class="tabs__download-button">Download</button>
type

2023-02-28 09:16 UTC, UladTeachMeSkills commented on exit_project/main.html
> +                  <button class="tabs__download-button">Download</button>
same

2023-02-28 09:16 UTC, UladTeachMeSkills commented on exit_project/main.html
> +                  src="/fe-46-yarmak/exit_project/images/liberty_statue.svg"
same

2023-02-28 09:16 UTC, UladTeachMeSkills commented on exit_project/main.html
> +        <a href="#"><img src="./images/rss.svg" alt="rss" /></a>
Открыть ссылку на соответствующий ресурс в новом окне

2023-03-01 08:22 UTC, AlyonaY commented on exit_project/main.html
> +              <label class="tabs__item" id="tab-three" for="three">Tab 3</label>
для бордера

2023-03-01 08:25 UTC, AlyonaY commented on exit_project/main.html
> +        <a href="#"><img src="./images/rss.svg" alt="rss" /></a>
уже в мейне

2023-03-02 07:28 UTC, UladTeachMeSkills approved these changes

2023-03-06 16:36 UTC, merged