completed banner_2
AlyonaY/fe-46-yarmak pull request #2
Opened 2023-02-05 17:18 UTC by AlyonaY

2023-02-05 21:09 UTC, UladTeachMeSkills requested changes

2023-02-05 21:09 UTC, UladTeachMeSkills commented on exit_project/main.html
> +    <link href="/fe-46-yarmak/exit_project/styles/common.css" rel="stylesheet" />
Почему такой странный путь у всех link?
Используй ./styles/...

2023-02-05 21:09 UTC, UladTeachMeSkills commented on exit_project/main.html
> +    <link href="/fe-46-yarmak/exit_project/styles/banner.css" rel="stylesheet" />
Перепроверь все ссылки в файле. Везде ссылка должна начинаться с "./"

2023-02-05 21:09 UTC, UladTeachMeSkills commented on exit_project/styles/banner.css
> +    url(/fe-46-yarmak/exit_project/images/banner_background.svg);
Нужна точка перед слешем

2023-02-05 21:09 UTC, UladTeachMeSkills commented on exit_project/styles/banner.css
> +  font-family: "Raleway";
Не исправлены предыдущие комментарии в коде

2023-02-06 20:28 UTC, AlyonaY commented on exit_project/styles/banner.css
> +    url(/fe-46-yarmak/exit_project/images/banner_background.svg);
у меня через точку только css файлы находит , а через полный путь можно на картинки указать

2023-02-07 07:27 UTC, UladTeachMeSkills commented on exit_project/styles/banner.css
> +    url(/fe-46-yarmak/exit_project/images/banner_background.svg);
А если найду?)
./images/banner_background.svg

2023-02-07 08:43 UTC, AlyonaY commented on exit_project/styles/banner.css
> +    url(/fe-46-yarmak/exit_project/images/banner_background.svg);
я так писала, но у меня тогда нет картинки на сайте(

2023-02-19 16:06 UTC, merged