footer+social
AlyonaY/fe-46-yarmak pull request #4
Opened 2023-02-12 21:52 UTC by AlyonaY

2023-02-13 10:43 UTC, UladTeachMeSkills requested changes

2023-02-13 10:43 UTC, UladTeachMeSkills commented on exit_project/main.html
> +    <section class="footer_dark">
Footer сам по себе семантический тег, обозначающий секцию

2023-02-13 10:43 UTC, UladTeachMeSkills commented on exit_project/main.html
> +      <footer>
Можно использовать только его, без обёртки

2023-02-13 10:43 UTC, UladTeachMeSkills commented on exit_project/styles/common.css
> +@import url("https://fonts.googleapis.com/css2?family=Raleway&display=swap");
Используй пожалуйста импорт шрифтов только в одном файле.

2023-02-13 10:43 UTC, UladTeachMeSkills commented on exit_project/styles/common.css
> +    font-weight: 400;
Выбери одно семейство шрифтов которое ты определишь в основном теге body.
Все остальные повторения font-family - удали во всех остальных файлах стилей. Используй только локально в классе для переопределения на какой-то другой шрифт

2023-02-13 10:43 UTC, UladTeachMeSkills commented on exit_project/styles/social_media.css
> +  font-family: "Open Sans";
Выбери одно семейство шрифтов которое ты определишь в основном теге body.
Все остальные повторения font-family - удали во всех остальных файлах стилей. Используй только локально в классе для переопределения на какой-то другой шрифт

2023-02-13 11:01 UTC, AlyonaY commented on exit_project/styles/common.css
> +@import url("https://fonts.googleapis.com/css2?family=Raleway&display=swap");
исправление шрифтов в другой ветке не замерженное

2023-02-13 11:10 UTC, AlyonaY commented on exit_project/styles/common.css
> +    font-weight: 400;
исправление шрифтов в другой ветке

2023-02-13 11:10 UTC, AlyonaY commented on exit_project/styles/social_media.css
> +  font-family: "Open Sans";
исправление шрифтов в другой ветке

2023-02-14 15:01 UTC, UladTeachMeSkills approved these changes

2023-02-16 09:46 UTC, merged