header+media
AlyonaY/fe-46-yarmak pull request #5
Opened 2023-02-19 15:54 UTC by AlyonaY

2023-02-21 07:49 UTC, UladTeachMeSkills requested changes

2023-02-21 07:49 UTC, UladTeachMeSkills commented on exit_project/main.html
> +    <link href="./styles/common.css" rel="stylesheet" />
Собери все ссылки в один файл index.css при помощи @import url().
Импортируй свой файл index.css в main.html при помощи link

2023-02-21 07:49 UTC, UladTeachMeSkills commented on exit_project/main.html
> +              <li><a href="#">Contact</a></li>
Сделай ссылки на соответствующие id секций, что бы можно было пролистывать страницу к ним

2023-02-21 07:49 UTC, UladTeachMeSkills commented on exit_project/main.html
> +        <a href="#"><img src="./images/rss.svg" alt="rss" /></a>
Добавь ссылки на соответствующие медиаресурсы что бы они открывались в новом окне

2023-02-21 07:49 UTC, UladTeachMeSkills commented on exit_project/styles/common.css
> +@import url(./header.css);
Эмм, это надо добавить в index.css

2023-02-21 07:49 UTC, UladTeachMeSkills commented on exit_project/styles/common.css
>  @import url("https://fonts.googleapis.com/css2?family=Raleway&display=swap");
У тебя должен быть основной файл css в котором будет два импорта шрифтов, тег body с установленным шрифтом и общие переиспользуемые классы, такие как .container и т.д.

2023-02-21 07:49 UTC, UladTeachMeSkills commented on exit_project/styles/header.css
> +  flex-direction: row;
Не обязательно

2023-02-21 07:49 UTC, UladTeachMeSkills commented on exit_project/styles/header.css
> +  flex-direction: row;
same

2023-02-21 07:49 UTC, UladTeachMeSkills commented on exit_project/styles/header.css
> +  flex-direction: row;
same

2023-02-21 08:27 UTC, AlyonaY commented on exit_project/main.html
> +    <link href="./styles/common.css" rel="stylesheet" />
это в мейн ветке уже, только у меня не index а common называется общий файл

2023-02-21 08:29 UTC, AlyonaY commented on exit_project/styles/common.css
> +@import url(./header.css);
у меня называется не index, а common. это и есть общий файл

2023-02-27 13:21 UTC, AlyonaY commented on exit_project/main.html
> +        <a href="#"><img src="./images/rss.svg" alt="rss" /></a>
fixed in another branch

2023-02-27 14:34 UTC, AlyonaY commented on exit_project/main.html
> +              <li><a href="#">Contact</a></li>
сделаю в мейне, где будут все секции

2023-02-28 09:19 UTC, UladTeachMeSkills approved these changes

2023-02-28 16:36 UTC, merged