Reviews
AlyonaY/fe-46-yarmak pull request #8
Opened 2023-02-26 11:50 UTC by AlyonaY

2023-02-27 08:46 UTC, UladTeachMeSkills requested changes

2023-02-27 08:46 UTC, UladTeachMeSkills commented on exit_project/main.html
> +    <section class="banner_1">
Недопустимое имя класса "_1"

2023-02-27 08:46 UTC, UladTeachMeSkills commented on exit_project/main.html
> +              <button class="banner_1__download-button">Download</button>
type

2023-02-27 08:46 UTC, UladTeachMeSkills commented on exit_project/main.html
> +              <a href="#"><img src="./images/logo_big.svg" alt="logo" /></a>
Это скорее просто изображение, чем ссылка

2023-02-27 08:46 UTC, UladTeachMeSkills commented on exit_project/main.html
> +        <a href="#"><img src="./images/rss.svg" alt="rss" /></a>
Добавь ссылки на соответствующие ресурсы с открытием в новом окне

2023-02-27 13:11 UTC, AlyonaY commented on exit_project/main.html
> +    <section class="banner_1">
fixed in another branch

2023-02-28 09:18 UTC, UladTeachMeSkills approved these changes

2023-02-28 16:57 UTC, merged